/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407xx.h"

int main(void)
{
	GPIO_Handle_t *LED_0;


	GPIO_PeriClockControl(GPIOF, ENABLE);

	LED_0->pGPIOBaseAddr = GPIOF;
	LED_0->GPIO_PinConfig.PinAltFunMode = 0;
	LED_0->GPIO_PinConfig.PinMode = GPIO_MODE_OUTPUT;
	LED_0->GPIO_PinConfig.PinNumber = GPIO_PINNUM_9;
	LED_0->GPIO_PinConfig.PinOPType = GPIO_OP_TYPE_PP;
	LED_0->GPIO_PinConfig.PinPuPdControl = GPIO_PUPD_NO_PUPD;
	LED_0->GPIO_PinConfig.PinSpeed = GPIO_SPEED_LOW;

	GPIO_Init(LED_0);
	/* Loop forever */

	while(1)
	{
		GPIO_ToggleOutputPin(GPIOF,GPIO_PINNUM_9);
		for(uint32_t i=0; i<500000;i++);
	}

	return 0;
}
