/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f407xx.h"

uint8_t Btn_1_St = 0;

int main(void)
{
	//LED GPIO Def
	GPIO_Handle_t *GPIO_Cfg;
	GPIO_PeriClockControl(GPIOF, ENABLE);
	GPIO_Cfg->pGPIOBaseAddr = GPIOF;
	GPIO_Cfg->GPIO_PinConfig.PinAltFunMode = 0;
	GPIO_Cfg->GPIO_PinConfig.PinMode = GPIO_MODE_OUTPUT;
	GPIO_Cfg->GPIO_PinConfig.PinNumber = GPIO_PINNUM_9;
	GPIO_Cfg->GPIO_PinConfig.PinOPType = GPIO_OP_TYPE_OD;
	GPIO_Cfg->GPIO_PinConfig.PinPuPdControl = GPIO_PUPD_PU;
	GPIO_Cfg->GPIO_PinConfig.PinSpeed = GPIO_SPEED_HI;
	GPIO_Init(GPIO_Cfg);

	//Button GPIO Def
	GPIO_PeriClockControl(GPIOE, ENABLE);
	GPIO_Cfg->pGPIOBaseAddr = GPIOE;
	GPIO_Cfg->GPIO_PinConfig.PinAltFunMode = 0;
	GPIO_Cfg->GPIO_PinConfig.PinMode = GPIO_MODE_IT_RT;
	GPIO_Cfg->GPIO_PinConfig.PinNumber = GPIO_PINNUM_3;
	GPIO_Cfg->GPIO_PinConfig.PinOPType = 0x0;
	GPIO_Cfg->GPIO_PinConfig.PinPuPdControl = GPIO_PUPD_PU;
	GPIO_Cfg->GPIO_PinConfig.PinSpeed = GPIO_SPEED_HI;
	GPIO_Init(GPIO_Cfg);

	GPIO_IRQConfig(IRQ_NO_EXTI3, 0x01, ENABLE); //Enable IRQ

	/* Loop forever */
	while(1)
	{
		//Btn_1_St = GPIO_ReadInputPin(GPIOE, GPIO_PINNUM_3);

		if(Btn_1_St == 0)
		{
			GPIO_ToggleOutputPin(GPIOF,GPIO_PINNUM_9);
			for(uint32_t i=0; i<500000;i++);
		}
	}

	return 0;
}

void EXTI3_IRQHandler(void)
{
	GPIO_IRQHandling(3);
	//Btn_1_St = Btn_1_St == 1 ? 1:0;
	Btn_1_St ^= 1;
}
